name: ci
on: [push, pull_request]
jobs:
  make-build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: makeInit
        run: |
          make LZMA=0 ZSTD=0 MD5=0 -j
      - name: makeUnDef
        run: |
          git clone --depth=1 https://github.com/sisong/libmd5.git ../libmd5
          git clone -b fix-make-build --depth=1 https://github.com/sisong/lzma.git ../lzma
          git clone -b v1.5.2 --depth=1 https://github.com/facebook/zstd.git ../zstd
          make DIR_DIFF=0 MT=0 BSD=0 ZLIB=0 BZIP2=0 -j
      - name: makeAll
        run: |
          make -j
      - name: makeByCode
        run: |
          git clone --depth=1 https://github.com/sisong/zlib.git ../zlib
          git clone --depth=1 https://github.com/sisong/bzip2.git ../bzip2
          make ZLIB=1 BZIP2=1 -j

  clang-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: installClang
        run: |
          sudo apt-get install -y llvm clang
      - name: initAndClone
        run: |
          git clone --depth=1 https://github.com/sisong/libmd5.git ../libmd5
          git clone -b fix-make-build --depth=1 https://github.com/sisong/lzma.git ../lzma
          git clone -b v1.5.2 --depth=1 https://github.com/facebook/zstd.git ../zstd
      - name: makeByClang
        run: |
          make CL=1 -j

  xcode-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: initAndClone
        run: |
          git clone --depth=1 https://github.com/sisong/libmd5.git ../libmd5
          git clone -b fix-make-build --depth=1 https://github.com/sisong/lzma.git ../lzma
          git clone -b v1.5.2 --depth=1 https://github.com/facebook/zstd.git ../zstd
      - name: buildByXcode
        run: |
          xcodebuild -workspace builds/xcode/HDiffPatch.xcworkspace -scheme hdiffz -configuration Release OBJROOT=$PWD/bin SYMROOT=$PWD/bin
          xcodebuild -workspace builds/xcode/HDiffPatch.xcworkspace -scheme hpatchz -configuration Release OBJROOT=$PWD/bin SYMROOT=$PWD/bin
          xcodebuild -workspace builds/xcode/HDiffPatch.xcworkspace -scheme unitTest -configuration Release OBJROOT=$PWD/bin SYMROOT=$PWD/bin

  ndk-build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1.0.6
        with:
          ndk-version: r16b
      - name: buildByAndroidNDK
        run: |
          git clone -b fix-make-build --depth=1 https://github.com/sisong/lzma.git ../lzma
          cd ./builds/android_ndk_jni_mk
          ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk

  vc-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: initAndClone
        run: |
          git clone --depth=1 https://github.com/sisong/zlib.git ../zlib
          git clone --depth=1 https://github.com/sisong/bzip2.git ../bzip2
          git clone --depth=1 https://github.com/sisong/libmd5.git ../libmd5
          git clone -b fix-make-build --depth=1 https://github.com/sisong/lzma.git ../lzma
          git clone -b v1.5.2 --depth=1 https://github.com/facebook/zstd.git ../zstd
      - name: buildByVC
        run: |
          msbuild builds/vc2019/HDiffPatch.sln -t:rebuild -verbosity:diag -property:Configuration=Release
